# CI Completa - Trabalho de Conclusão

name: Pipeline Self-Hosted - Testes Backend e Frontend

on:
  workflow_dispatch: #Execução manual

jobs:       
  unitarios:
    runs-on: self-hosted #Roda em um ambiente definido pelo usuario, podendo ser local ou cloud. 

    strategy:
      matrix:
        app:
          - name: backend
            test: test:backend
            junit: backend/test-results/backend-junit.xml
            coverage: backend/coverage

          - name: frontend
            test: test:frontend
            junit: frontend/test-results/frontend-junit.xml
            coverage: frontend/coverage

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5 

      - name: Criar arquivo .env
        run: |
          echo "CHARACTER=${{ secrets.CHARACTER }}" >> .env

      - name: Configurar Node.js
        uses: actions/setup-node@v6 
        with:
          node-version: 24.x
      
      - name: Instalar dependências
        run: npm ci #Roda mais rápido por usar o -lock e evita conflito de versões

      - name: Executar testes (${{ matrix.app.name }})
        run: npm run ${{ matrix.app.test }}
      
      - name: Publicar resultados de teste
        if: always() # Garante que os resultados sejam publicados mesmo se os testes falharem
        uses: dorny/test-reporter@v2
        with:
          name: ${{ matrix.app.name }}-test-results
          path: ${{ matrix.app.junit }}
          reporter: java-junit
      
      - name: Salvando coverage
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.app.coverage }}
          name: ${{ matrix.app.name }}-coverage

  deploy:
    runs-on: self-hosted
    needs: [unitarios]

    steps:
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado...'